services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker  --entryPoints.web.address=:80 --entryPoints.admin.address=:3000
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  static:
    build: ./php-apache
    scale: 3
    labels:
      - "traefik.http.routers.static.rule=Host(`localhost`)"
      - "traefik.http.routers.static.entrypoints=web"
      - "traefik.http.services.webapp.loadbalancer.server.port=80"
  dynamic:
    build: ./express-image
    scale: 3
    labels:
      - "traefik.http.routers.dynamic.rule=Host(`localhost`)"
      - "traefik.http.services.dynamic.loadbalancer.server.port=3000"
      - "traefik.http.routers.dynamic.middlewares=dynamic-stripprefix"
      - "traefik.http.middlewares.dynamic-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.dynamic.rule=Host(`localhost`) && Path(`/api`)"